### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/PythonRemoteServer#17]
This would be especially handy because Robot Framework itself doesn't yet support Python 3. Most likely we will target Python 3.3 or newer and will at the same time drop support from versions prior to Python/Jython 2.5.

**Comment by mkorpela** [comment]
Pabot will not support Python 3 before this is done

https://github.com/mkorpela/pabot/issues/54

invalid syntax (robotremoteserver.py, line 103)

**Comment by molsky** [comment]
I have tried to implement Python3 support but 24 acceptance tests are failing with Python3 and I have not yet figured out why. With Python2.7 atests and utests goes with 100% success.

Changes:
https://github.com/molsky/PythonRemoteServer/tree/python2-3

![screen shot 2016-08-17 at 11 09 55 2](https://cloud.githubusercontent.com/assets/1943521/17730127/06e730a2-6470-11e6-91ad-1b16680998ed.png)

![screen shot 2016-08-17 at 11 43 46 2](https://cloud.githubusercontent.com/assets/1943521/17730131/0c8b0024-6470-11e6-9753-5bf7559fe73b.png)

**Comment by userzimmermann** [comment]
Hi @molsky 
Great work :) I took your approach a bit further:
https://github.com/userzimmermann/PythonRemoteServer/tree/python2-3

Only 3 failing atests left with python3, but all due to different unicode string display in comparison.
@pekkaklarck Those well known `Expected error 'Hyv\xe4' but got 'Hyvä'.` like problems from my earlier robotframework-python3 fork... ;) How did you unify those tests in robotframework 3.0?

BTW: Is the **six** dependency ok or better replace with custom definitions?

**Comment by pekkaklarck** [comment]
The code should now support Python 3. Acceptance tests run successfully with Python 3.3-3.6 both on Linux and Windows and also with PyPy 3 on Linux.

Tasks still todo:
- Go through docs. Should update them to mention Python 3 is supported and also that we support PyPy.
- Update setup.py. Need to add correct classifiers there.
