### ISSUE TITLE
Starting server on background

### ISSUE THREAD

**Issue by mkorpela** [robotframework/PythonRemoteServer#22]
The init currently calls serve_forever() that prevents execution from continuing.
Init also registers signal handlers - this is only allowed in the main thread.
Thus currently it is not possible to start the server on background and continuing working on something else on the main thread.

**Comment by pekkaklarck** [comment]
Yeah, this is stupid design. Shouldn't be too hard to fix,

**Comment by pekkaklarck** [comment]
Turned out to be much more work than I anticipated but ought to be pretty much ready now.

@mkorpela do you have time to test this and perhaps also to review the code?

Functionality is documented in the [README](https://github.com/robotframework/PythonRemoteServer/blob/master/README.rst) and also in docstrings in the code. Documentation comments are obviously appreciated too.

**Comment by pekkaklarck** [comment]
This ought to be now supported and 1.1 RC 1 is also out. Testing the functionality and reviewing the related documentation in the README would be highly appreciated.
