### ISSUE TITLE
Question - Help Please

### ISSUE THREAD

**Issue by VarunJoshi** [robotframework/PythonRemoteServer#63]
Hi,

I have the python remote server running on one machine. See screenshot (connectionerror.png)
![connectionerror](https://user-images.githubusercontent.com/1350186/81214068-48160580-8fa5-11ea-833c-aeab83444b6f.PNG)

And I am trying to run a selenium test from another machine calling the keywords from the above machine. But I get this error (seleniumtesterror.png). 
![seleniumtesterror](https://user-images.githubusercontent.com/1350186/81214069-48160580-8fa5-11ea-8479-0dadb880e2db.PNG)

I would appreciate if you can help me figure out what I am doing wrong. Thanks!

![image](https://user-images.githubusercontent.com/1350186/81214178-74ca1d00-8fa5-11ea-9cfd-b8992d4ad8e3.png)

**Comment by pekkaklarck** [comment]
Unfortunately at least I don't have any idea what's going wrong. GET should definitely be supported. Did you test the example that's part of this project? Testing the setup so that everything runs on the same machine would be a good idea as well.

This issue tracker isn't really a support forum but rather a place for bug reports and enhancement requests. I'll thus close this issue but if you find an actual bug somewhere please submit a new one. You can also ask help on various community forums listed at http://robotframework.org.

**Comment by VarunJoshi** [comment]
Is there no support forum for PythonRemoteServer?

**Comment by pekkaklarck** [comment]
There's no dedicated forum/channel for PythonRemoteServer, but you can use the generic ones like the mailing list or Slack.
